form.fileupload.remove=remove
form.fileupload.editFileUpload=Configure File Upload
form.fileupload.id=ID
form.fileupload.invalidId=Only alpha-numeric and underscore characters allowed
form.fileupload.label=Label
form.fileupload.size=Size
form.fileupload.readonly=Readonly
form.fileupload.chooseValidator=Choose Validator
form.fileupload.validator=Validator
form.fileupload.download=Download as Attachment
form.fileupload.maxSize=Maximum File Size per File (KB)
form.fileupload.fileType=File Type (.pdf;.doc)
form.fileupload.maxSize.msg=Error Message (File size limit exceeded)
form.fileupload.maxSize.msg.fileTooBig=File size limit exceeded
form.fileupload.fileType.msg=Error Message (File type mismatch)
form.fileupload.fileType.msg.invalidFileType=Invalid file type
form.fileupload.invalidSize=Only number allowed
form.fileupload.advancedOptions=Advanced Options
form.fileupload.data=Data
form.fileupload.ui=UI
form.fileupload.multiple=Enable Multiple Files Upload
form.fileupload.customPermission=Custom Permission
form.fileupload.permission.loggedInUsers=Logged In Users
form.fileupload.permission.public=Public
form.fileupload.permission.custom=Custom
form.fileupload.removeFile=Delete Actual File During Overwrite or Removal?
form.fileupload.dropFile=Drop files here or click to upload.
form.fileupload.dropzonePadding=Drop Zone Padding
form.fileupload.resize=Image Resize
form.fileupload.resizeWidth=Maximum Width (px)
form.fileupload.resizeHeight=Maximum Height (px)
form.fileupload.resizeQuality=Quality (Max 1.0)
form.fileupload.resizeMethod=Method
form.fileupload.contain=Contain
form.fileupload.crop=Crop

org.joget.marketplace.PPTFileUload.Configuration= PPT File Upload Configuration
org.joget.marketplace.pptFile.slideShowIcon=Configure Slide Show Icon
org.joget.marketplace.pptfileupload.slideShowIcon= View Slide Show Icon
org.joget.marketplace.pptfileupload.viewIconColor=View Icon Color

